spring:
  application:
    name: backend

  datasource:
    url: jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=DB_Production;trustServerCertificate=true;encryption=false;
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

api:
  prefix: api/v1
