spring:
  application:
    name: backend

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DB_Production;trustServerCertificate=true;encrypt=false;
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080